version: "3.7"

services:
  web:
    container_name: web
    networks:
      - network-django
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./web:/app/web
    depends_on:
      - db
    links:
      - db
    command: ["./entrypoint.sh"]
    ports:
      - "9000:8000"

  db:
    container_name: db
    networks:
      - network-django
    image: postgres:12-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=django_web
      - POSTGRES_PASSWORD=django_web
      - POSTGRES_DB=django_web
    command: ["--autovacuum=off"]
    ports:
      - "5432:5432"

networks:
  network-django:

volumes:
  db:
